"""criar tabela categorias

Revision ID: 29289653762c
Revises: df2f53a964a6
Create Date: 2026-03-16 19:24:56.616602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29289653762c'
down_revision: Union[str, Sequence[str], None] = 'df2f53a964a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.add_column('produtos', sa.Column('categoria_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'produtos', 'categorias', ['categoria_id'], ['id'])
    op.drop_column('produtos', 'categoria')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('categoria', sa.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'produtos', type_='foreignkey')
    op.drop_column('produtos', 'categoria_id')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
